const WEATHER_TOKEN = import.meta.env.VITE_WEATHER_TOKEN;
const GOOGLE_MAPS_KEY = import.meta.env.VITE_GOOGLE_MAPS_KEY;

window.WEATHER_TOKEN = WEATHER_TOKEN;
window.GOOGLE_MAPS_KEY = GOOGLE_MAPS_KEY;
